CREATE TABLE user(
	user_id BIGINT(100) AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(100) NOT NULL,
	nick_name VARCHAR(100) NOT NULL,
	name VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE my_condition(
	condition_id BIGINT(100) AUTO_INCREMENT PRIMARY KEY,
	preset_name VARCHAR(100) DEFAULT NULL,
	addr_do VARCHAR(100) DEFAULT NULL,
	addr_si VARCHAR(100) DEFAULT NULL,
	addr_gu VARCHAR(100) DEFAULT NULL,
	addr_dong VARCHAR(100) DEFAULT NULL,
	addr_daero VARCHAR(100) DEFAULT NULL,
	addr_detail VARCHAR(100) DEFAULT NULL,
	budget INT(100) DEFAULT 0,
	activate VARCHAR(1) DEFAULT 'N',
	my_condition BIGINT(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE items(
	item_id BIGINT(100) AUTO_INCREMENT PRIMARY KEY,
	head_addr VARCHAR(100) NOT NULL,
	addr_jibun VARCHAR(100) NOT NULL,
	addr_road VARCHAR(100) DEFAULT NULL,
	price INT(100) NOT NULL,
	owner_id BIGINT(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
